#!/bin/bash
__sc_to_module_fish_completion() {
    module=$1
    description=$2
    echo "complete -f -c sc -n '__fish_sc_needs_command' -a $module -d $description"
}

__sc_to_module_commands_fish_completion() {
    module=$1
    __print_completion() {
        echo "complete -f -c sc -n '__fish_sc_using_command $module' -a $1 -d \"$2\""
    }
    for cmd in $(__sc_command_names $module); do
        __print_completion $cmd "$(__sc_command_docstring $module $cmd)"
    done
}
