#!/bin/bash
__sc_to_module_fish_completion() {
    module=$1
    description=$2
    echo "complete -f -c sc -n '__fish_sc_needs_command' -a $module -d $description"
}

__sc_to_module_commands_fish_completion() {
    module=$1
    IFS=$'\n'
    for command_name in $(__sc_command_names $module); do
        docstring="$(__sc_command_docstring $module $command_name)"
        docstring_quoted=$(printf "%q\n" "$docstring")
        echo "complete -f -c sc -n '__fish_sc_using_command $module' -a $command_name -d $docstring_quoted"
    done
    unset IFS
}

### generate fish completions file
# get all function names and docstrings
# print a completion line with the function name as the "option"
# and the docstring as the "description"
cat $__sc_DATA_DIR/meta/fish-completions-header
for module in ${__sc_MODULES[@]}; do
    docstring=$(__sc_module_docstring $module)
    docstring_quoted=$(printf "%q\n" "$docstring")
    __sc_to_module_fish_completion $module "$docstring_quoted"
    __sc_to_module_commands_fish_completion $module
    echo
done
