#!/bin/bash
source "$__sc_MODULES_DIR/meta/_common"

### generate fish completions file
# get all function names and docstrings
# print a completion line with the function name as the "option"
# and the docstring as the "description"
cat $__sc_DATA_DIR/meta/fish-completions-header
for module in ${__sc_MODULES[@]}; do
    docstring=$(__sc_module_docstring $module)
    docstring_quoted=$(printf "%q\n" "$docstring")
    __sc_to_module_fish_completion $module "$docstring_quoted"
    __sc_to_module_commands_fish_completion $module
    echo
done
