#!/bin/bash
### sparse aws shortcuts (deprecated)

_aws_list-profiles() { ### list aws profiles'
    if [ -f ~/.aws/config ]; then
        grep '\[.*\]' ~/.aws/config | sed -e 's/\[profile//g' -e 's/\]//g' | tr -d ' '
    else
        echo 'No ~/.aws/config' >&2
    fi
}

# for any zone
_aws_list-ssm-params() { ### list ssm parameters
    # if [ $# -lt 1 ]; then
    #     echo 'usage: list-ssm-params'
    #     exit 1
    # fi
    # --query "Parameters[?Type=='SecureString']" \
    aws ssm describe-parameters \
        --query "Parameters" \
        $* \
        | jq '.[].Name' \
        | __sc_remove_json_artifacts
}

# for any zone
_aws_get-ssm-param() { ### get and decrypt an ssm parameter
    if [ $# -lt 1 ]; then
        echo 'usage: get-ssm-param NAME'
        exit 1
    fi
    name=$1; shift
    aws ssm get-parameter \
        --name "$name" \
        --with-decryption \
        | jq .Parameter.Value \
        | __sc_remove_json_artifacts
}
