#!/bin/bash

_dns_short_help() {
    echo "Route53 shortcuts"
}

_dns() {
    echo "$(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  list-zones - list route53 hosted zones"
    echo "  list-build - list route53 DNS records for stage"
    echo "  list-com   - list route53 DNS records for production"
    echo "  list-zone  - list route53 DNS records for the given zone id"
    echo
    echo "example:"
    echo "  list-com | jq '.[] | .Name' | tr -d '\"' | grep -v '\.xid\.' | sed 's/\.$//g' > /tmp/segment.com.noxid.json"
}

_dns_list-zones() {
    aws route53 list-hosted-zones $*
}

# segment.build.
_dns_list-build() {
    echo Getting A and CNAME records for segment.build... 1>&2
    aws route53 list-resource-record-sets \
        --hosted-zone-id='/hostedzone/Z14S3MNCOH1TH2' \
        --query "ResourceRecordSets[?Type=='A' || Type=='CNAME']" \
        $*
}

# segment.com.
_dns_list-com() {
    echo Getting A and CNAME records for segment.com... 1>&2
    aws route53 list-resource-record-sets \
        --hosted-zone-id='/hostedzone/Z1JLJR02Q3PHKP' \
        --query "ResourceRecordSets[?Type=='A' || Type=='CNAME']" \
        $*
} 

_dns_list-zones() {
    aws route53 list-hosted-zones $* \
        | jq '[ .HostedZones[] | { name: .Name, zone: .Id } ]'
}

# for any zone
_dns_list-zone() {
    if [ $# -lt 1 ]; then
        echo 'usage: list-zone AWS_ZONE_ID (run list-zones for a list)'
        exit 1
    fi
    zone_id=$1; shift
    echo Getting A and CNAME records for $zone_id... 1>&2
    aws route53 list-resource-record-sets \
        --hosted-zone-id="${zone_id}" \
        # --query "ResourceRecordSets[?Type=='A' || Type=='CNAME']" \
        $*
} 
