#!/bin/bash
### sparse ecr shortcuts

source $__sc_CONFIG_DIR/aws-config

_ecr_list-repos() { ### list ECR repositories
    aws ecr describe-repositories \
        | jq '[ .repositories[] | {name: .repositoryName, arn: .repositoryArn, uri: .repositoryUri } ]'
}

_ecr_list-images() { ### list images in a repository
    if [ $# -lt 1 ]; then
        echo 'usage: list-images REPO_NAME (run list-repos for a list)'
        exit 1
    fi
    repo_name=$1; shift
    echo Getting images for $repo_name... 1>&2
    aws ecr list-images --repository-name $repo_name \
        | jq '[ .imageIds[] | { tag: .imageTag, digest: .imageDigest } ]'
}

_ecr_login() { ### log into ecr with default profile
    exec $(aws-vault exec ${AWS_VAULT_DEFAULT_PROFILE} -- aws ecr get-login --no-include-email)
}
