#!/bin/bash

_git_short_help() {
    echo "Slack conveniences"
}

_git() {
    echo "$(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  remove-from-history - Fully remove a file from git history"
}

_git_remove-from-history() {
    __warn 'This is a destructive command, so you have to run it yourself:'
    echo
    cat <<EOF
git filter-branch --force --index-filter \\
    'git rm --cached --ignore-unmatch YOUR_FILE_HERE' \\
    --prune-empty --tag-name-filter cat -- --all
EOF
}
