#!/bin/bash

_github_short_help() {
    echo "github shortcuts"
}

_github() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  list-repos - list all repo names for an org"
}

_github_list-repos() {
    if [ $# -lt 1 ]; then
        echo 'usage: list-repos kind name'
        echo
        echo '`kind` - one of "users" or "orgs"'
        exit 1
    fi
    kind=$1
    name=$2

    for repo in $(curl -Ls "https://api.github.com/$kind/$name/repos?per_page=200" \
        | jq '.[].name' \
        | tr -d \"); do
        echo $name $repo
    done
}
