#!/bin/bash
### Lambda shortcuts

_lambda_list() { ### list lambda functions
    aws lambda list-functions \
        | jq '[ .Functions[] | { name: .FunctionName, arn: .FunctionArn } ]'
}

_lambda_show() { ### show lambda function details
    if [ $# -lt 1 ]; then
        echo 'usage: show FUNCTION_NAME (run list for a list)'
        exit 1
    fi
    fn_name=$1; shift
    aws lambda get-function --function-name $fn_name $*
}

_lambda_show-env() { ### show environment variables for a function
    if [ $# -lt 1 ]; then
        echo 'usage: show-env FUNCTION_NAME'
        exit 1
    fi
    _lambda_show $1 | jq '.Configuration | { function: .FunctionName, vars: .Environment.Variables }'
}

_lambda_show-envs() { ### show environment variables for a list of functions
    if [ $# -lt 1 ]; then
        echo 'usage: show-envs [FUNCTION_NAME...]'
        exit 1
    fi
    for name in $@; do
        _lambda_show-env $name
    done | jq -s
}

# doesn't work, haven't tried to debug
_lambda_show-env-all() { ### show environment variables for all functions (in the region) (broken)
    __info "Getting lambda envs (nothing will show until we're done)"
    for name in $(_lambda_list | jq '.[].name' | tr -d \"); do
        __info "Getting env for $name" 1>&2
        _lambda_show-env $name
    done | jq -s
}
