#!/bin/bash

meta_short_help() {
    echo "meta things"
}

meta() {
    echo "$(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  list-profiles - list aws profiles"
}

meta_list-profiles() {
    if [ -f ~/.aws/config ]; then
        grep '\[.*\]' ~/.aws/config | sed -e 's/\[profile//g' -e 's/\]//g' | tr -d ' '
    else
        echo 'No ~/.aws/config' >&2
    fi
}
