#!/bin/bash

__SETUP_DIR=$__BASEDIR/setup

_meta_short_help() {
    echo "setup stuff I guess"
}

_meta() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  search      - search for a command"
    echo "  setup       - install/build deps"
    echo "  edit-source - edit source for a module"
}

_meta_search() {
    __search_usage() {
        echo usage: search TERM
        exit 1
    }
    if [ $# -lt 1 ]; then
        __search_usage
    fi
    term=$1; shift
    echo matching commands:
    grep -hior -e "^_.*${term}.*()" ${__BASEDIR}/modules \
        | grep -v short_help \
        | sed -e 's/_/ /g' -e 's/^ /  /g' -e 's/()//g'
}

_meta_setup() {
    __setup_usage() {
        echo usage: setup ITEM
        echo
        echo available items
        echo "  all - setup everything below"
        ls $__setup_usage | sed "s/^/  /g"
        exit 1
    }
    if [ $# -lt 1 ]; then
        __setup_usage
    fi
    name=$1; shift
    case $name in
        all)
            for d in $__SETUP_DIR; do
                __info setting up $d
                $d/setup
            done
            ;;
        *)
            if ! [ -f $__SETUP_DIR/$name/setup ]; then
                __error $name is not recognized as a setup item
                __setup_usage
            fi
            __info setting up $name
            $__SETUP_DIR/$name/setup
            ;;
    esac
}

_meta_edit-source() {
    if [ $# -ne 1 ]; then
        echo usage: edit-source MODULE
    fi

    module=$__BASEDIR/modules/$1
    if ! [ -f $module ]; then
        echo no module "$module"
    else
        $__EDITOR $module
    fi
}
