#!/bin/bash
_net_short_help() {
    echo "Network shortcuts"
}

_net() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  proxy      - proxy with netcat"
    echo "  cert-chain - get the cert chain for a TLS endpoint"
    echo "  wayback    - do a wayback machine search (opens a browser)"
}

_net_proxy() {
    # TODO -v is not logging connection?
    if ! [ $# -eq 3 ]; then
        echo 'usage: net proxy LISTENING_PORT REMOTE PORT'
        exit 1
    fi
    listen_port=$1
    remote_host=$2
    remote_port=$3

    fifo=/tmp/_nc-proxy-fifo-$(head -c 12 /dev/urandom | xxd -p)
    _cleanup() { rm $fifo; }
    trap _cleanup EXIT

    mkfifo $fifo
    __info Made fifo $fifo
    __info Listening on $listen_port, proxying to $remote_host:$remote_port
    nc -vl $listen_port < $fifo | nc $remote_host $remote_port > $fifo
}

_net_cert-chain() {
    if [ $# -lt 1 ]; then
        echo 'usage: net cert-chain DOMAIN [PORT]'
        exit 1
    fi
    domain=$1
    port=${2:-443}
    openssl s_client -connect $domain:$port </dev/null 2>/dev/null
}

_net_wayback() {
    if [ $# -lt 1 ]; then
        echo 'usage: wayback SITE'
        exit 1
    fi
	__info 'h/t @verysmallegg'
	prefix='http://web.archive.org/web/*/'
    query=$prefix$1
    __link_open $query
}
