#!/bin/bash
### stuff that might not be useful at all

_scratch_qemu() {
    if [ $# -ne 1 ]; then
        echo 'usage: qemu PATH_TO_ISO'
        exit 1
    fi
    image_path=$1
    __info "Why? fuck if I know"
    qemu-system-x86_64 \
        -m 1024 \
        -boot d \
        -accel hvf \
        -smp 3 \
        -net nic \
        -net user \
        -hda testing-image.img \
        -cdrom ${image_path}
}

