#!/bin/bash

SHARK_BASE_DIR=~/src/security/shark

_sec_short_help() {
    echo "Security tool shortcuts"
}

_sec() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  trufflehog      - run trufflehog (you can pass args)"
    echo "  grep-todo       - grep common todo strings in pwd"
    echo "  test-aws-key    - grep common todo strings in pwd"
    echo "  check-fish-read - check if fish has saved any secrets typed into read -s"
    echo "  shark           - run some shit against a target"
    echo "  nmap            - nmap some shit"
    echo "  payload         - cat a payload (no args to list available)"
    echo "  scrape          - start local bookmark scraper listener"
}

_sec_trufflehog() {
    if ! [ -f ~/.venvs/utils/bin/trufflehog ]; then
        __warn "Couldn't find ~/.venvs/utils/bin/trufflehog"
        __warn "Either set that up, or set SC_TRUFFLEHOG_PATH"
        exit 1
    fi
    TRUFFLEHOG=${SC_TRUFFLEHOG_PATH:-~/.venvs/utils/bin/trufflehog}
    ${TRUFFLEHOG} \
        --regex \
        --entropy false \
        --rules $(dirname ${BASH_SOURCE[0]})/../config/trufflehog-rules.json \
        $*
}

_sec_grep-todo() {
    fifo="/tmp/$(head -c4 /dev/urandom | xxd -p | xargs).fifo"
    mkfifo $fifo
    # dumb mkfifo tee hack (tee >(subcmd) syntax may not be available)
    echo -e "----\n$(wc -l < $fifo | xargs) todos found" &
    {
        if git status &>/dev/null; then
            git grep --color=always -ie '\btodo\b' -e '\bxxx\b' -e '\bfixme\b'
        else
            grep --color=always -ire '\btodo\b' -e '\bxxx\b' -e '\bfixme\b' .
        fi
    } | tee $fifo
    rm $fifo
}

_sec_test-aws-key() {
    read -p "Key ID (AKIA...): " _key_id
    read -sp "Secret (will be hidden): " _key_secret
    echo

    __info calling aws sts-get-caller-identity with $_key_id
    env -i \
        PATH=$(dirname $(which aws))
        AWS_ACCESS_KEY_ID=${_key_id} \
        AWS_SECRET_ACCESS_KEY=${_key_secret} \
        aws sts get-caller-identity
}

_sec_payload() {
    _basedir=$(dirname ${BASH_SOURCE[0]})/../data/sec
    _usage() { echo "usage: payload TYPE NAME"; }
    _category=$1
    _subcategory=$2
    _name=$3
    if [ -z "$_category" ]; then
        echo available categories
        ls $_basedir | sed 's/^/  /g'
        exit 0
    elif [ -z "$_subcategory" ]; then
        echo available $_category types
        ls $_basedir/$_category | sed 's/^/  /g'
        exit 0
    elif [ -z "$_name" ]; then
        echo available $_category/$_subcategory payloads
        ls $_basedir/$_category/$_subcategory | sed 's/^/  /g'
        exit 0
    elif [ $# -gt 3 ]; then
        _usage
    else
        grep -o "^#.*$" $_basedir/$_category/$_subcategory/$_name >&2
        grep -v "^#.*$" $_basedir/$_category/$_subcategory/$_name
    fi
}

_sec_check-fish-read() {
    __info "This is hardcoded for the default path" >&2
    __info "You should make it check for alternate configuration" >&2
    cat ~/.local/share/fish/fish_read_history
}

_sec_shark() {
    if [ $# -lt 1 ]; then
        echo 'usage: shark target [n_top_ports_to_nmap(25)]'
        exit 1
    fi
    target=$1
    outdir=${2:-$SHARK_BASE_DIR}
    outfile_base=$outdir/$target
    echo $@

    __info will output under $outdir, enter to continue
    read

    mkdir -p $outdir

    dig $target | tee ${outfile_base}-dig
    # whois $target | tee -a ${outfile_base}-whois
    # -o doesn't work (in fact, new amass update... doesn't seem to do anything)
    amass enum -d $target | tee ${outfile_base}-amass
}

_sec_nmap() {
    if [ $# -lt 1 ]; then
        echo 'usage: nmap target [n_top_ports_to_nmap(25)] [speed(3)]'
        exit 1
    fi
    target=$1
    n_top_ports=${2:-25}
    speed=${3:-3}
    nmap -vvv -T${speed} -Pn --top-ports=$n_top_ports $target
}

_sec_scrape() {
    __scrape_usage() {
        echo 'usage: scrape [start|get] [options..]'
        echo
        echo Listen on localhost for data from bookmarklet-based scrapers
        echo
        echo subcommands:
        echo '    start (run) [port]'
        echo '    get kind [port]'

        exit 1
    }

    if [ $# -lt 1 ]; then
        __scrape_usage
    fi

    cmd=$1; shift
    case $cmd in
        start|run)
            port=${1:-9753}
            echo starting scraper on port $port
            ${__BASEDIR}/bin/scrape-listener -p $port run
            ;;
        get)
            kind=${1:_}
            port=${2:-9753}
            curl -sL localhost:$port/_/$kind
            ;;
        *)
            __scrape_usage
            ;;
    esac
}
