#!/bin/bash
_segment_short_help() {
    echo "segment things"
}

_segment() {
    echo "$(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  auth-gateway - authenticate to the app via gateway-api"
}

_segment_auth-gateway() {
    email=$1
    if [ -z $email ]; then
        read -p 'email: ' email >&2
    fi
    read -p 'password (input will be hidden): ' -s password >&2
    host=https://gateway-api.segment.com/graphql

read -r -d '' payload <<PAYLOAD
{
  "query": "mutation auth(\$email:String!, \$password:String!) {login(email:\$email, password:\$password)}",
  "variables": {
    "email": "$email",
    "password": "$password"
  }
}
PAYLOAD
    echo

    token=$(curl -s $host \
        -H "Content-Type: application/json" \
        -d "$payload" \
        | jq '.data.login.access_token' \
        | sed 's/"//g')

    if [ $token = "null" ]; then
        __error authentication error 1>&2
    else
        echo $token
    fi
}
