#!/bin/bash

shell_short_help() {
    echo "various shell shortcuts"
}

shell() {
    echo "$(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  tee-cmd   - portable tee to a command (when >() isn't available)"
}

# TODO: trap errors and clean up instead of doing this?
shell_tee-cmd() {
    __error This doesn\'t work at the moment.
    exit 1
    if [ $# -lt 2 ] || ! [ "$1" = "--" ] ; then
        echo 'usage: <cmd> | sc shell tee-cmd -- command [args..]'
        exit 1
    fi
    shift  # get rid of the --
    cmdstr=$@
    tempfile="/tmp/$(head -c 6 /dev/urandom | xxd -p | xargs).fifo"
    mkfifo $tempfile
    $cmdstr < $tempfile &
    tee | $tempfile
    rm $tempfile
}
