#!/bin/bash

_slack_short_help() {
    echo "Slack conveniences"
}

_slack() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  post-webhook - send slack-flavored markdown"
}

_slack_post-webhook() {
    if [ $# -lt 2 ]; then
        echo "usage: ${FUNCNAME[0]} WEBHOOK TEXT"
        exit 1
    fi
	curl -X POST \
		-H 'Content-type: application/json' \
		--data "{\"mrkdwn\":true,\"text\":\"${2}\"}" \
        $1
}
