#!/bin/bash
### slack shortcuts

_slack_post-webhook() { ### send slack-flavored markdown
    if [ $# -lt 2 ]; then
        echo "usage: ${FUNCNAME[0]} WEBHOOK TEXT"
        echo
        echo "Note: Slack responds 'no_text' if posting empty string to valid webhook, 'invalid_token' to invalid webhook"
        exit 1
    fi
    _slack_url=$1; shift
    curl -X POST \
      -H 'Content-type: application/json' \
      --data "{\"mrkdwn\":true,\"text\":\"${@}\"}" \
        $_slack_url
}
