#!/bin/bash

_utils_short_help() {
    echo "Miscellaneous"
}

_utils() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  view-json           - pretty view json (jq -C into a pager) (better than bat!)"
    echo "  calc                - do simple calculations with bc (calc '1/2*5.1')"
    echo "  print-unicode       - print a unicode character by codepoint"
    echo "  start-elasticsearch - kinda wacky"
    echo "  stop-elasticsearch  - kinda wacky"
}

_utils_view-json() {
    if [ $# -eq 1 ] && [ "$1" = "-h" ]; then
        echo 'usage: view-json FILE or view-json < file'
        exit 1
    fi
    if [ $# -eq 1 ]; then
        jq -C . < $1 | less -R
    else
        cat | jq -C . | less -R
    fi
}

_utils_calc() {
    if ! [ $# -eq 1 ]; then
        echo 'example usage: calc "1/2*5"'
        exit 1
    fi
    __warn fyi this is only outputting 6 decimals
    echo "scale=6; $1" | bc -liq
}

_utils_print-unicode() {
    if ! [ $# -eq 1 ]; then
        echo 'example usage: print-unicode 200B'
        exit 1
    fi
    _codepoint=$1
    __info depending on the codepoint, you may not see any output >&2
    python3 -c 'print("\u'${_codepoint}'", end=None)'
}

_utils_start-elasticsearch() {
    __info 'This is definitely one of the less necessary things in here'
    docker-compose -f ${__BASEDIR}/config/docker-compose-es.yml up
}

_utils_stop-elasticsearch() {
    __info 'This is definitely one of the less necessary things in here'
    docker-compose -f ${__BASEDIR}/config/docker-compose-es.yml down
}
