#!/bin/bash

### module description

_{{name}}_subcommand() {  ### subcommand description
    __sc_requires_one_of nc ncat
    if [ $# -lt 1 ]; then
        echo 'usage: subcommand args'
        exit 1
    fi
    __sc_success hello "$@"
}
