#!/bin/bash

### module description

_{{name}}_command() {  ### command description
    __sc_requires_one_of nc ncat
    if [ $# -lt 1 ]; then
        echo 'usage: command args'
        exit 1
    fi
    __sc_success hello "$@"
}
