#!/bin/bash

_{{name}}_short_help() {
    echo "todo"
}

_{{name}}() {
    echo "usage: $(basename $0) ${FUNCNAME[0]} subcommand"
    echo
    echo "available subcommands are:"
    echo "  subcommand - todo"
}

_{{name}}_subcommand() {
    if [ $# -lt 1 ]; then
        echo 'usage: subcommand args'
        exit 1
    fi
    __error todo
}
