version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
